### ISSUE TITLE
Make and check backend CRUD routes

### ISSUE THREAD

**Issue by Mark-LohseMiranda** [POlsen-92/TableTop-FrontEnd#10]
Controller Files
- [x] Users
- [x] Campaign
- [x] Characters
- [x] Blog Posts
- [x] Comment Posts
- [x] UserCampaign
- [x] Invite
- [x] Inventory
- [ ] Character Presets ?
- [ ] Tag Routes ?

**Comment by POlsen-92** [comment]
- [ ] Create User
- [ ] Create Campaign
- [ ] Create Character within Campaign
- [ ] Create Character Presets

- [ ] Read User
- [ ] Read Campaign
- [ ] Read Character
- [ ] Read Character Presets

- [ ] Update User
- [ ] Update Campaign
- [ ] Update Character
- [ ] Update Character Presets

- [ ] Delete User
- [ ] Delete Campaign
- [ ] Delete Character
- [ ] Delete Character Presets
